### ISSUE TITLE
feat: Change the Color of button after Selecting 

### ISSUE THREAD

**Issue by rohit-vitofficial** [rohit-vitofficial/Quiz-App#3]
The option should be changed in red for wrong answer and green for the right ans
![image](https://github.com/rohit-vitofficial/Quiz-App/assets/147172043/8fb4c627-b856-473a-96d1-8a3fbcad1003)

**Comment by Tejas-1511** [comment]
Hey can I work on this issue?

**Comment by rohit-vitofficial** [comment]
sure
